# Generated by Django 3.2.12 on 2024-04-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_alter_myprodect_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincategory',
            name='offer',
        ),
    ]
